"""Kaggriculture single-file submission compiler."""

import os


def compile_submission():
    # Relative root path to support any machine environment
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src_dir = os.path.join(root_dir, "src")
    sub_path = os.path.join(root_dir, "submission", "submission.py")

    # Order of modules to prevent definition/ordering dependency failures
    modules = [
        "env/state.py",
        "env/transitions.py",
        "env/parser.py",
        "utils/routing.py",
        "utils/market.py",
        "utils/calculators.py",
        "utils/state_featurizer.py",
        "agents/base.py",
        "agents/heuristic.py",
        "agents/mcts.py",
        "agents/escalation.py",
    ]

    out_lines = [
        '"""Kaggriculture compiled standalone agent submission file.',
        "Auto-generated by compile_submission.py.",
        '"""',
        "import random",
        "import math",
        "from dataclasses import dataclass, replace",
        "from abc import ABC, abstractmethod",
        "from typing import Tuple, Dict, Optional, NamedTuple",
        "",
    ]

    for mod in modules:
        mod_path = os.path.join(src_dir, mod)
        if not os.path.exists(mod_path):
            continue

            # Parse files and strip localized imports
        with open(mod_path, encoding="utf-8") as f:
            lines = f.readlines()

        out_lines.append(f"# === MODULE: {mod} ===")
        for line in lines:
            # Strip localized imports referencing our workspace layouts
            if "from src." in line or "import src." in line:
                continue
            # Strip imports already resolved at the global level
            if (
                line.startswith("import random")
                or line.startswith("import math")
                or line.startswith("from dataclasses")
                or line.startswith("from abc")
                or line.startswith("from typing")
            ):
                continue
            out_lines.append(line.rstrip())
        out_lines.append("")
        out_lines.append("")

    # Add the submission execution entrypoint
    entrypoint = [
        "# === AGENT ENTRYPOINT ===",
        "agent = MCTSAgent()",
        "",
        "def agent_entrypoint(obs_json: dict) -> dict:",
        "    # 1. Parse raw observation",
        "    state = parse_world_state(obs_json)",
        "    # 2. Query actions",
        "    joint_actions = agent.act(state)",
        "    # 3. Format output compatible with Kaggle match engine",
        "    return {",
        '        "farmer": joint_actions.get("worker_actions", {}).get(1, ["PASS"]),',
        '        "market": joint_actions.get("farm_actions", [])',
        "    }",
    ]
    out_lines.extend(entrypoint)

    os.makedirs(os.path.dirname(sub_path), exist_ok=True)
    with open(sub_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines))

    print(f"Successfully compiled submission file to: {sub_path}")


if __name__ == "__main__":
    compile_submission()
