"""Kaggriculture compiled standalone agent submission file.
Auto-generated by compile_submission.py.
"""
import random
import math
from dataclasses import dataclass, replace
from abc import ABC, abstractmethod
from typing import Tuple, Dict, Optional, NamedTuple

# === MODULE: env/state.py ===
"""Kaggriculture immutable game state representation."""



@dataclass(frozen=True, slots=True)
class CropState:
    """State of an individual crop on the grid."""

    crop_type: str
    growth_stage: int  # 0: Seed, 1: Sprout, 2: Mature, 3: Harvestable
    moisture: int  # Moisture level (0 to 100)
    is_watered: bool
    x: int
    y: int


@dataclass(frozen=True, slots=True)
class AnimalState:
    """State of an individual animal on the farm."""

    animal_type: str  # "Cow", "Sheep", "Chicken"
    hunger: int  # Hunger level (0 to 100)
    is_fed: bool
    x: int
    y: int


@dataclass(frozen=True, slots=True)
class WorkerState:
    """State of an individual hired agricultural worker."""

    worker_id: int
    x: int
    y: int
    carrying: str | None  # Name of item carried or None
    is_busy: bool


@dataclass(frozen=True, slots=True)
class FarmState:
    """State of the player's farm financial and resource accounts."""

    gold: int
    inventory: dict[str, int]  # Map of item_name -> count
    workers: tuple[WorkerState, ...]
    expansion_quadrants: int  # Number of expanded quadrants purchased


@dataclass(frozen=True, slots=True)
class WorldState:
    """The overarching global world state of Kaggriculture."""

    turn: int  # 0 to 720
    weather: str  # "Sunny", "Rainy", "Overcast"
    grid_width: int
    grid_height: int
    crops: tuple[CropState, ...]
    animals: tuple[AnimalState, ...]
    farm: FarmState
    tilled_tiles: tuple[tuple[int, int], ...]  # List of coordinates currently tilled


@dataclass(frozen=True, slots=True)
class StrategicTarget:
    """Target resource objectives selected by the high-level MCTS Strategic Brain."""

    target_workers: int
    target_cows: int
    target_sheep: int
    target_geese: int
    crop_priorities: dict[str, int]
    budget_reserved_for_seeds: float
    is_liquidating: bool


# === MODULE: env/transitions.py ===
"""Kaggriculture pure, stateless transition functions."""




def step_crop(crop: CropState, watered: bool, weather: str) -> CropState:
    """Updates the state of a single crop based on watering and weather.

    Decay rules:
    - Sunny: -10 moisture
    - Rainy: +15 moisture
    - Overcast: -5 moisture

    Watering adds +30 moisture (capped at 100).
    Optimal moisture range is 20 to 90. If optimal, and either watered or
    rainy weather, growth stage advances.
    """
    # Calculate new moisture
    decay = 0
    if weather == "Sunny":
        decay = -10
    elif weather == "Rainy":
        decay = 15
    elif weather == "Overcast":
        decay = -5

    new_moisture = crop.moisture + decay
    if watered:
        new_moisture += 30

    new_moisture = max(0, min(100, new_moisture))

    # Growth stage progression
    new_growth = crop.growth_stage
    is_optimal = 20 <= new_moisture <= 90
    has_water_source = watered or weather == "Rainy" or crop.is_watered

    if is_optimal and has_water_source and crop.growth_stage < 3:
        new_growth += 1

    return CropState(
        crop_type=crop.crop_type,
        growth_stage=new_growth,
        moisture=new_moisture,
        is_watered=watered or (weather == "Rainy"),
        x=crop.x,
        y=crop.y,
    )


def get_fibonacci_number(n: int) -> int:
    """Returns the n-th Fibonacci number (1-indexed: 1, 1, 2, 3, 5, 8...)."""
    if n <= 0:
        return 0
    if n == 1:
        return 1
    a, b = 1, 1
    for _ in range(3, n + 1):
        a, b = b, a + b
    return b


def step_world(state: WorldState, joint_actions: dict) -> WorldState:
    """Executes tilling, planting, harvesting, watering, caring, and hiring actions.

    Joint actions format:
    {
        "worker_actions": {
            worker_id: ("TILE", x, y) | ("PLANT", x, y, crop_type) |
                       ("WATER", x, y) | ("HARVEST", x, y) |
                       ("FEED", x, y) | ("MOVE", direction)
        },
        "farm_actions": ["HIRE_WORKER", "BUY_EXPANSION"]
    }
    """
    # Update weather
    next_weather = (
        random.choice(["Sunny", "Rainy", "Overcast"])
        if state.turn % 5 == 0
        else state.weather
    )

    # Current state views
    tilled = set(state.tilled_tiles)
    crops_map = {(c.x, c.y): c for c in state.crops}
    animals_map = {(a.x, a.y): a for a in state.animals}
    workers_list = list(state.farm.workers)
    gold = state.farm.gold
    inventory = dict(state.farm.inventory)
    expansion = state.farm.expansion_quadrants

    worker_actions = joint_actions.get("worker_actions", {})
    farm_actions = joint_actions.get("farm_actions", [])

    # Process Farm-level actions
    for action in farm_actions:
        if action == "HIRE_WORKER":
            next_worker_idx = len(workers_list) + 1
            cost = 100 * get_fibonacci_number(next_worker_idx)
            if gold >= cost:
                gold -= cost
                new_worker = WorkerState(
                    worker_id=next_worker_idx,
                    x=0,
                    y=0,
                    carrying=None,
                    is_busy=False,
                )
                workers_list.append(new_worker)
        elif action == "BUY_EXPANSION":
            cost = 1000 * (2**expansion)
            if gold >= cost:
                gold -= cost
                expansion += 1

    # Process Worker-level actions and update coordinates/state
    updated_workers = []
    for w in workers_list:
        act = worker_actions.get(w.worker_id)
        if not act:
            updated_workers.append(w)
            continue

        act_type = act[0]

        if act_type == "MOVE":
            direction = act[1]
            nx, ny = w.x, w.y
            if direction == "UP" and w.y > 0:
                ny -= 1
            elif direction == "DOWN" and w.y < state.grid_height - 1:
                ny += 1
            elif direction == "LEFT" and w.x > 0:
                nx -= 1
            elif direction == "RIGHT" and w.x < state.grid_width - 1:
                nx += 1
            updated_workers.append(
                WorkerState(
                    worker_id=w.worker_id,
                    x=nx,
                    y=ny,
                    carrying=w.carrying,
                    is_busy=w.is_busy,
                )
            )

        elif act_type == "TILE":
            tx, ty = act[1], act[2]
            # Must be adjacent to worker to tile (Manhattan distance <= 1)
            if abs(w.x - tx) + abs(w.y - ty) <= 1:
                tilled.add((tx, ty))
            updated_workers.append(w)

        elif act_type == "PLANT":
            tx, ty, c_type = act[1], act[2], act[3]
            if (
                abs(w.x - tx) + abs(w.y - ty) <= 1
                and (tx, ty) in tilled
                and (tx, ty) not in crops_map
            ):
                # Remove from tilled, add to crops
                tilled.discard((tx, ty))
                crops_map[(tx, ty)] = CropState(
                    crop_type=c_type,
                    growth_stage=0,
                    moisture=50,
                    is_watered=False,
                    x=tx,
                    y=ty,
                )
            updated_workers.append(w)

        elif act_type == "WATER":
            tx, ty = act[1], act[2]
            if abs(w.x - tx) + abs(w.y - ty) <= 1 and (tx, ty) in crops_map:
                crops_map[(tx, ty)] = step_crop(
                    crops_map[(tx, ty)], watered=True, weather=state.weather
                )
            updated_workers.append(w)

        elif act_type == "HARVEST":
            tx, ty = act[1], act[2]
            if abs(w.x - tx) + abs(w.y - ty) <= 1 and (tx, ty) in crops_map:
                crop = crops_map[(tx, ty)]
                if crop.growth_stage == 3:  # Harvestable
                    inventory[crop.crop_type] = inventory.get(crop.crop_type, 0) + 1
                    del crops_map[(tx, ty)]
                    tilled.add((tx, ty))  # Returns to tilled state
            updated_workers.append(w)

        elif act_type == "FEED":
            ax, ay = act[1], act[2]
            if abs(w.x - ax) + abs(w.y - ay) <= 1 and (ax, ay) in animals_map:
                anim = animals_map[(ax, ay)]
                animals_map[(ax, ay)] = AnimalState(
                    animal_type=anim.animal_type,
                    hunger=max(0, anim.hunger - 40),
                    is_fed=True,
                    x=anim.x,
                    y=anim.y,
                )
            updated_workers.append(w)
        else:
            updated_workers.append(w)

    # Step crops that were not explicitly watered this turn
    for (cx, cy), crop in crops_map.items():
        # Check if this crop was watered via worker water actions
        watered_by_action = False
        for act in worker_actions.values():
            if act[0] == "WATER" and act[1] == cx and act[2] == cy:
                watered_by_action = True
                break
        if not watered_by_action:
            crops_map[(cx, cy)] = step_crop(crop, watered=False, weather=state.weather)

    # Step animal states (hunger increase)
    for (ax, ay), anim in animals_map.items():
        new_hunger = min(100, anim.hunger + 10)
        animals_map[(ax, ay)] = AnimalState(
            animal_type=anim.animal_type,
            hunger=new_hunger,
            is_fed=False,
            x=anim.x,
            y=anim.y,
        )

    return WorldState(
        turn=state.turn + 1,
        weather=next_weather,
        grid_width=state.grid_width,
        grid_height=state.grid_height,
        crops=tuple(crops_map.values()),
        animals=tuple(animals_map.values()),
        farm=FarmState(
            gold=gold,
            inventory=inventory,
            workers=tuple(updated_workers),
            expansion_quadrants=expansion,
        ),
        tilled_tiles=tuple(sorted(tilled)),
    )


# === MODULE: env/parser.py ===
"""Kaggriculture Kaggle observation dictionary/array parser."""



def parse_world_state(obs: dict) -> WorldState:
    """Parses a nested Kaggle observation dict into the WorldState domain structure."""
    raw_crops = obs.get("crops", [])
    crops_list = []
    for c in raw_crops:
        crops_list.append(
            CropState(
                crop_type=c["crop_type"],
                growth_stage=c["growth_stage"],
                moisture=c["moisture"],
                is_watered=c.get("is_watered", False),
                x=c["x"],
                y=c["y"],
            )
        )

    raw_animals = obs.get("animals", [])
    animals_list = []
    for a in raw_animals:
        animals_list.append(
            AnimalState(
                animal_type=a["animal_type"],
                hunger=a["hunger"],
                is_fed=a.get("is_fed", False),
                x=a["x"],
                y=a["y"],
            )
        )

    raw_farm = obs.get("farm", {})
    raw_workers = raw_farm.get("workers", [])
    workers_list = []
    for w in raw_workers:
        workers_list.append(
            WorkerState(
                worker_id=w["worker_id"],
                x=w["x"],
                y=w["y"],
                carrying=w.get("carrying"),
                is_busy=w.get("is_busy", False),
            )
        )

    farm_state = FarmState(
        gold=raw_farm.get("gold", 0),
        inventory=dict(raw_farm.get("inventory", {})),
        workers=tuple(workers_list),
        expansion_quadrants=raw_farm.get("expansion_quadrants", 0),
    )

    raw_tilled = obs.get("tilled_tiles", [])
    tilled_tiles = tuple((int(t[0]), int(t[1])) for t in raw_tilled)

    return WorldState(
        turn=obs.get("turn", 0),
        weather=obs.get("weather", "Sunny"),
        grid_width=obs.get("grid_width", 10),
        grid_height=obs.get("grid_height", 10),
        crops=tuple(crops_list),
        animals=tuple(animals_list),
        farm=farm_state,
        tilled_tiles=tilled_tiles,
    )


# === MODULE: utils/routing.py ===
"""Kaggriculture Manhattan routing and pathfinding utilities."""


def manhattan_distance(x1: int, y1: int, x2: int, y2: int) -> int:
    """Calculates Manhattan distance between two 2D coordinates."""
    return abs(x1 - x2) + abs(y1 - y2)


def find_shortest_path(
    start_x: int, start_y: int, end_x: int, end_y: int
) -> list[tuple[str, str]]:
    """Generates a sequence of move commands towards the target tile.

    Returns:
        List of tuples: [("MOVE", direction), ...]
    """
    path = []
    curr_x, curr_y = start_x, start_y

    while curr_x != end_x:
        if curr_x < end_x:
            path.append(("MOVE", "RIGHT"))
            curr_x += 1
        else:
            path.append(("MOVE", "LEFT"))
            curr_x -= 1

    while curr_y != end_y:
        if curr_y < end_y:
            path.append(("MOVE", "DOWN"))
            curr_y += 1
        else:
            path.append(("MOVE", "UP"))
            curr_y -= 1

    return path


# === MODULE: utils/market.py ===
"""Kaggriculture market prioritizing and sequential order utilities."""

PREMIUM_GOODS = {"Milk", "Wool", "Strawberries", "Melons"}


def sort_market_commands(commands: list[dict]) -> list[dict]:
    """Sorts market sell actions so premium goods appear at the front.

    Assumes commands are dicts or tuples representing transactions:
    {"action": "SELL", "item": str, "quantity": int}
    """

    def priority_key(cmd: dict) -> int:
        item = cmd.get("item", "")
        # Return 0 for premium, 1 for normal
        return 0 if item in PREMIUM_GOODS else 1

    return sorted(commands, key=priority_key)


# === MODULE: utils/calculators.py ===
"""Kaggriculture wage, expansion, and yield mathematical calculators."""



def get_worker_wage(worker_index: int, base_wage: int = 100) -> int:
    """Calculates Fibonacci-scaled worker hiring wage contract."""
    return base_wage * get_fibonacci_number(worker_index)


def get_expansion_cost(quadrant_index: int, base_cost: int = 1000) -> int:
    """Calculates exponential land expansion cost."""
    return base_cost * (2**quadrant_index)


def estimate_crop_yield(
    moisture: int, crop_type: str, has_care_bonus: bool = False
) -> float:
    """Estimates the yield of a crop based on moisture, type, and care bonuses.

    Crops suffer optimal moisture range penalties (optimal is 20 to 90).
    Outside of optimal bounds, yield drops significantly.
    Care bonus provides a 1.25x multiplier on the resulting yield.
    """
    base_yield = 1.0
    if crop_type in {"Strawberries", "Melons"}:
        base_yield = 1.5

    # Moisture penalty factor (penalize if too dry or flooded)
    moisture_factor = 1.0 if 20 <= moisture <= 90 else 0.4

    yield_val = base_yield * moisture_factor
    if has_care_bonus:
        yield_val *= 1.25

    return round(yield_val, 2)


# === MODULE: utils/state_featurizer.py ===
"""Kaggriculture state featurizer converting WorldState to flat 2D numpy arrays."""

import numpy as np



def featurize_state(state: WorldState) -> dict[str, np.ndarray]:
    """Converts the WorldState into a dict of flat or 2D NumPy feature matrices.

    Features generated:
    - "tilled": 2D grid where tilled cells are 1.0, others are 0.0.
    - "growth": 2D grid containing crop growth stages (0-3).
    - "moisture": 2D grid containing crop moisture levels (0-100 normalized to 0.0-1.0).
    - "workers": 2D grid containing worker locations.
    """
    w, h = state.grid_width, state.grid_height

    # Pre-allocate grids
    tilled_grid = np.zeros((h, w), dtype=np.float32)
    growth_grid = np.zeros((h, w), dtype=np.float32)
    moisture_grid = np.zeros((h, w), dtype=np.float32)
    workers_grid = np.zeros((h, w), dtype=np.float32)

    # Populate tilled tiles
    for tx, ty in state.tilled_tiles:
        if 0 <= tx < w and 0 <= ty < h:
            tilled_grid[ty, tx] = 1.0

    # Populate crop states
    for crop in state.crops:
        cx, cy = crop.x, crop.y
        if 0 <= cx < w and 0 <= cy < h:
            growth_grid[cy, cx] = float(crop.growth_stage)
            moisture_grid[cy, cx] = float(crop.moisture) / 100.0

    # Populate worker positions
    for worker in state.farm.workers:
        wx, wy = worker.x, worker.y
        if 0 <= wx < w and 0 <= wy < h:
            workers_grid[wy, wx] += 1.0

    return {
        "tilled": tilled_grid,
        "growth": growth_grid,
        "moisture": moisture_grid,
        "workers": workers_grid,
    }


# === MODULE: agents/base.py ===
"""Kaggriculture abstract base agent interface."""




class BaseAgent(ABC):
    """Abstract base agent for Kaggriculture decisions."""

    @abstractmethod
    def act(self, state: WorldState) -> dict:
        """Determines actions for all workers and the farm.

        Args:
            state: The current WorldState snapshot.

        Returns:
            dict: Joint actions structure, containing:
                  {
                      "worker_actions": {worker_id: ActionTuple},
                      "farm_actions": [FarmActionsList]
                  }
        """


# === MODULE: agents/heuristic.py ===
"""Kaggriculture greedy heuristic-based rule agent with strategic target support."""



class HeuristicAgent(BaseAgent):
    """Greedy rule-based agent prioritizing critical farm duties."""

    def __init__(self, crop_to_plant: str = "Strawberries"):
        self.crop_to_plant = crop_to_plant

    def act(self, state: WorldState, target: StrategicTarget | None = None) -> dict:
        """Determines prioritized actions driven by a strategic target."""
        # 1. Fallback / default target if none is supplied
        if target is None:
            target = StrategicTarget(
                target_workers=3,
                target_cows=0,
                target_sheep=0,
                target_geese=0,
                crop_priorities={self.crop_to_plant: 10},
                budget_reserved_for_seeds=100.0,
                is_liquidating=False,
            )

        worker_actions = {}
        farm_actions = []

        # Current livestock counts
        cows = sum(1 for a in state.animals if a.animal_type == "Cow")
        sheep = sum(1 for a in state.animals if a.animal_type == "Sheep")
        geese = sum(1 for a in state.animals if a.animal_type == "Goose")

        # Current crop counts
        active_crop_counts = {}
        for c in state.crops:
            active_crop_counts[c.crop_type] = active_crop_counts.get(c.crop_type, 0) + 1

        # 2. Macro Farm Actions (Hiring, Purchases)
        gold_available = state.farm.gold

        # Scale Labor
        if (
            len(state.farm.workers) < target.target_workers
            and gold_available >= 500 + target.budget_reserved_for_seeds
        ):
            farm_actions.append("HIRE_WORKER")
            gold_available -= 500

        # Purchase Cows (Cost $500)
        if (
            cows < target.target_cows
            and gold_available >= 500 + target.budget_reserved_for_seeds
        ):
            farm_actions.append("BUY_COW")
            gold_available -= 500
            cows += 1

        # Purchase Sheep (Cost $300)
        if (
            sheep < target.target_sheep
            and gold_available >= 300 + target.budget_reserved_for_seeds
        ):
            farm_actions.append("BUY_SHEEP")
            gold_available -= 300
            sheep += 1

        # Purchase Geese (Cost $150)
        if (
            geese < target.target_geese
            and gold_available >= 150 + target.budget_reserved_for_seeds
        ):
            farm_actions.append("BUY_GEESE")
            gold_available -= 150
            geese += 1

        # Compile sell actions for gathered inventory (Market front-running)
        sell_orders = []
        for item, qty in state.farm.inventory.items():
            if qty > 0:
                sell_orders.append(("SELL", item, qty))

        # Sort sell orders so premium goods are processed first (milk, wool, etc.)
        premium_goods = {"Milk", "Wool", "Strawberries", "Melons", "Eggs"}
        sell_orders.sort(key=lambda o: 0 if o[1] in premium_goods else 1)
        farm_actions.extend(sell_orders)

        # 3. Dynamic Task Allocation for Workers
        # Emergency tasks
        harvestable_crops = [c for c in state.crops if c.growth_stage == 3]
        hungry_animals = [a for a in state.animals if a.hunger >= 50]
        thirsty_crops = [c for c in state.crops if c.moisture <= 30]
        empty_tilled_tiles = list(state.tilled_tiles)

        # Filter out tilled tiles that already have crops
        crop_coords = {(c.x, c.y) for c in state.crops}
        empty_tilled_tiles = [
            tile for tile in empty_tilled_tiles if tile not in crop_coords
        ]

        # Determine best crop to plant based on targets and deficits
        best_crop_to_plant = self.crop_to_plant
        max_deficit = 0
        for crop_type, target_count in target.crop_priorities.items():
            deficit = target_count - active_crop_counts.get(crop_type, 0)
            if deficit > max_deficit:
                max_deficit = deficit
                best_crop_to_plant = crop_type

        assigned_tasks = set()

        for worker in state.farm.workers:
            # 1. HARVEST (Prioritized first)
            best_harvest = None
            best_dist = float("inf")
            for c in harvestable_crops:
                if (c.x, c.y) in assigned_tasks:
                    continue
                dist = manhattan_distance(worker.x, worker.y, c.x, c.y)
                if dist < best_dist:
                    best_dist = dist
                    best_harvest = c

            if best_harvest:
                if best_dist <= 1:
                    worker_actions[worker.worker_id] = (
                        "HARVEST",
                        best_harvest.x,
                        best_harvest.y,
                    )
                else:
                    path = find_shortest_path(
                        worker.x, worker.y, best_harvest.x, best_harvest.y
                    )
                    if path:
                        worker_actions[worker.worker_id] = path[0]
                assigned_tasks.add((best_harvest.x, best_harvest.y))
                continue

            # 2. FEED ANIMALS
            best_animal = None
            best_dist = float("inf")
            for a in hungry_animals:
                if (a.x, a.y) in assigned_tasks:
                    continue
                dist = manhattan_distance(worker.x, worker.y, a.x, a.y)
                if dist < best_dist:
                    best_dist = dist
                    best_animal = a

            if best_animal:
                if best_dist <= 1:
                    worker_actions[worker.worker_id] = (
                        "FEED",
                        best_animal.x,
                        best_animal.y,
                    )
                else:
                    path = find_shortest_path(
                        worker.x, worker.y, best_animal.x, best_animal.y
                    )
                    if path:
                        worker_actions[worker.worker_id] = path[0]
                assigned_tasks.add((best_animal.x, best_animal.y))
                continue

            # 3. WATER CROPS
            best_thirsty = None
            best_dist = float("inf")
            for c in thirsty_crops:
                if (c.x, c.y) in assigned_tasks:
                    continue
                dist = manhattan_distance(worker.x, worker.y, c.x, c.y)
                if dist < best_dist:
                    best_dist = dist
                    best_thirsty = c

            if best_thirsty:
                if best_dist <= 1:
                    worker_actions[worker.worker_id] = (
                        "WATER",
                        best_thirsty.x,
                        best_thirsty.y,
                    )
                else:
                    path = find_shortest_path(
                        worker.x, worker.y, best_thirsty.x, best_thirsty.y
                    )
                    if path:
                        worker_actions[worker.worker_id] = path[0]
                assigned_tasks.add((best_thirsty.x, best_thirsty.y))
                continue

            # 4. PLANT ON EMPTY TILLED TILES (driven by target deficits)
            best_tile = None
            best_dist = float("inf")
            for tile in empty_tilled_tiles:
                if tile in assigned_tasks:
                    continue
                dist = manhattan_distance(worker.x, worker.y, tile[0], tile[1])
                if dist < best_dist:
                    best_dist = dist
                    best_tile = tile

            if best_tile and not target.is_liquidating:
                tx, ty = best_tile
                if best_dist <= 1:
                    worker_actions[worker.worker_id] = (
                        "PLANT",
                        tx,
                        ty,
                        best_crop_to_plant,
                    )
                else:
                    path = find_shortest_path(worker.x, worker.y, tx, ty)
                    if path:
                        worker_actions[worker.worker_id] = path[0]
                assigned_tasks.add((tx, ty))
                continue

            # 5. DEFAULT TILL/MOVE IDLE (till nearest untilled tile to expand)
            target_x = (worker.x + 1) % state.grid_width
            target_y = worker.y
            if (
                target_x,
                target_y,
            ) not in state.tilled_tiles and not target.is_liquidating:
                if abs(worker.x - target_x) <= 1:
                    worker_actions[worker.worker_id] = ("TILE", target_x, target_y)
                else:
                    path = find_shortest_path(worker.x, worker.y, target_x, target_y)
                    if path:
                        worker_actions[worker.worker_id] = path[0]
            else:
                worker_actions[worker.worker_id] = ("MOVE", "RIGHT")

        return {"worker_actions": worker_actions, "farm_actions": farm_actions}


# === MODULE: agents/mcts.py ===
"""Kaggriculture Monte Carlo Tree Search (MCTS) agent."""




@dataclass
class MCTSNode:
    """A node in the MCTS tree, branching on macro StrategicTargets."""

    state: WorldState
    parent: "MCTSNode | None" = None
    target: StrategicTarget | None = None
    visits: int = 0
    value: float = 0.0
    children: list["MCTSNode"] = None

    def __post_init__(self):
        if self.children is None:
            self.children = []


class MCTSAgent(BaseAgent):
    """Monte Carlo Tree Search decision agent using stateless macro targets."""

    def __init__(self, num_simulations: int = 20, exploration_weight: float = 1.414):
        self.num_simulations = num_simulations
        self.exploration_weight = exploration_weight
        self.heuristic_fallback = HeuristicAgent()
        self.active_target: StrategicTarget | None = None

    def act(self, state: WorldState) -> dict:
        """Runs MCTS to select the best target, then acts heuristically."""
        if not state.farm.workers:
            return {"worker_actions": {}, "farm_actions": []}

        # 1. Check if we need to re-plan strategic targets
        # Re-plan at Turn 0, start of each day, or if we have no target yet
        should_replan = (
            self.active_target is None
            or state.turn == 0
            or state.turn % 24 == 0
            or self._is_target_achieved(state, self.active_target)
        )

        if should_replan:
            self.active_target = self._search_best_target(state)

        # 2. Execute the current strategic target hourly via the Heuristic Core
        return self.heuristic_fallback.act(state, target=self.active_target)

    def _is_target_achieved(self, state: WorldState, target: StrategicTarget) -> bool:
        """Determines if the active strategic target's counts are satisfied."""
        workers_satisfied = len(state.farm.workers) >= target.target_workers
        cows = sum(1 for a in state.animals if a.animal_type == "Cow")
        sheep = sum(1 for a in state.animals if a.animal_type == "Sheep")
        geese = sum(1 for a in state.animals if a.animal_type == "Goose")

        animals_satisfied = (
            cows >= target.target_cows
            and sheep >= target.target_sheep
            and geese >= target.target_geese
        )

        # Check crops
        crop_counts = {}
        for c in state.crops:
            crop_counts[c.crop_type] = crop_counts.get(c.crop_type, 0) + 1

        crops_satisfied = True
        for crop, count in target.crop_priorities.items():
            if crop_counts.get(crop, 0) < count:
                crops_satisfied = False
                break

        return workers_satisfied and animals_satisfied and crops_satisfied

    def _search_best_target(self, state: WorldState) -> StrategicTarget:
        """MCTS search over the set of candidate targets."""
        # Setup Candidates
        candidates = []

        if state.turn >= 680:
            # Late-game liquidation target
            candidates.append(
                StrategicTarget(
                    target_workers=len(state.farm.workers),
                    target_cows=0,
                    target_sheep=0,
                    target_geese=0,
                    crop_priorities={},
                    budget_reserved_for_seeds=0.0,
                    is_liquidating=True,
                )
            )
        else:
            # Focus 1: Baseline strawberry rush (high-yield)
            candidates.append(
                StrategicTarget(
                    target_workers=3,
                    target_cows=0,
                    target_sheep=0,
                    target_geese=0,
                    crop_priorities={"Strawberries": 10},
                    budget_reserved_for_seeds=100.0,
                    is_liquidating=False,
                )
            )
            # Focus 2: Self-sustaining livestock and wheat feed loop
            candidates.append(
                StrategicTarget(
                    target_workers=4,
                    target_cows=3,
                    target_sheep=1,
                    target_geese=0,
                    crop_priorities={"Wheat": 8, "Strawberries": 4},
                    budget_reserved_for_seeds=150.0,
                    is_liquidating=False,
                )
            )
            # Focus 3: Heavy scaling (5 hands, diversified pasture)
            candidates.append(
                StrategicTarget(
                    target_workers=5,
                    target_cows=2,
                    target_sheep=2,
                    target_geese=2,
                    crop_priorities={"Wheat": 10, "Strawberries": 10},
                    budget_reserved_for_seeds=200.0,
                    is_liquidating=False,
                )
            )

        root = MCTSNode(state=state)

        # Expand root immediately with candidates
        for target in candidates:
            root.children.append(MCTSNode(state=state, parent=root, target=target))

        for _ in range(self.num_simulations):
            # Selection (always select from root's direct children for macro choice)
            node = self._select_ucb(root)

            # Simulation (Rollout) guided by candidate target
            reward = self._rollout(node.state, node.target)

            # Backpropagation
            node.visits += 1
            node.value += reward
            root.visits += 1
            root.value += reward

        # Retrieve the target from the child with the highest average value
        best_child = max(
            root.children, key=lambda c: (c.value / c.visits) if c.visits > 0 else -1.0
        )
        return best_child.target if best_child.target else candidates[0]

    def _select_ucb(self, node: MCTSNode) -> MCTSNode:
        """Selects a child node using standard Upper Confidence Bound (UCB1)."""
        best_score = -float("inf")
        best_child = node.children[0]

        for child in node.children:
            if child.visits == 0:
                return child
            exploitation = child.value / child.visits
            exploration = self.exploration_weight * math.sqrt(
                math.log(node.visits) / child.visits
            )
            score = exploitation + exploration
            if score > best_score:
                best_score = score
                best_child = child

        return best_child

    def _rollout(self, state: WorldState, target: StrategicTarget) -> float:
        """Brief daily rollout of the fast simulator guided by the target."""
        curr_state = state
        depth = 48  # Simulate 2 full days forward
        start_gold = state.farm.gold

        for _ in range(depth):
            # Get tactical hourly worker actions for target
            joint_actions = self.heuristic_fallback.act(curr_state, target=target)
            try:
                curr_state = step_world(curr_state, joint_actions)
            except Exception:
                break

        # Value scoring: gold accumulated + asset values
        gold_gained = curr_state.farm.gold - start_gold
        cows = sum(1 for a in curr_state.animals if a.animal_type == "Cow")
        sheep = sum(1 for a in curr_state.animals if a.animal_type == "Sheep")
        geese = sum(1 for a in curr_state.animals if a.animal_type == "Goose")

        asset_valuation = cows * 400 + sheep * 240 + geese * 120
        # Add basic weight for inventory items
        asset_valuation += sum(curr_state.farm.inventory.values()) * 15

        return float(gold_gained + asset_valuation)


# === AGENT ENTRYPOINT ===
agent = MCTSAgent()

def agent_entrypoint(obs_json: dict) -> dict:
    # 1. Parse raw observation
    state = parse_world_state(obs_json)
    # 2. Query actions
    joint_actions = agent.act(state)
    # 3. Format output compatible with Kaggle match engine
    return {
        "farmer": joint_actions.get("worker_actions", {}).get(1, ["PASS"]),
        "market": joint_actions.get("farm_actions", [])
    }